//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DangKyHocPhanEntities : DbContext
    {
        public DangKyHocPhanEntities()
            : base("name=DangKyHocPhanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DangKyHocPhan> DangKyHocPhans { get; set; }
        public virtual DbSet<Diem> Diems { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<HocPhan> HocPhans { get; set; }
        public virtual DbSet<LichHoc_LopHocPhan> LichHoc_LopHocPhan { get; set; }
        public virtual DbSet<LichHoc_NhomThucHanh> LichHoc_NhomThucHanh { get; set; }
        public virtual DbSet<LopHocPhan> LopHocPhans { get; set; }
        public virtual DbSet<LopNienChe> LopNienChes { get; set; }
        public virtual DbSet<NhanVienPDT> NhanVienPDTs { get; set; }
        public virtual DbSet<NhomThucHanh> NhomThucHanhs { get; set; }
        public virtual DbSet<NienKhoa> NienKhoas { get; set; }
        public virtual DbSet<PhongHoc> PhongHocs { get; set; }
        public virtual DbSet<SinhVien> SinhViens { get; set; }
    }
}
