//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHoc_NhomThucHanh
    {
        public int ID_LichHoc_NhomTH { get; set; }
        public string ID_NhomThucHanh { get; set; }
        public string NgayHoc { get; set; }
        public string TietHoc { get; set; }
        public string ID_PhongHoc { get; set; }
    
        public virtual NhomThucHanh NhomThucHanh { get; set; }
        public virtual PhongHoc PhongHoc { get; set; }
    }
}
